name: Android NDK CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ANDROID_NDK_VERSION: "27.0.12077973"
  CMAKE_VERSION: "3.22.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Android Build Tools
        uses: android-actions/setup-android@v3
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
          cmake-version: ${{ env.CMAKE_VERSION }}
          sdk-components: "platform-tools,ndk;${{ env.ANDROID_NDK_VERSION }}"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Build NDK libraries
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon clean :assembleFordebug
          mkdir -p so_output
          find app/build/intermediates/stripped_native_libs/fordebug/out/lib -name "*.so" -exec cp {} so_output/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-ndk-libs
          path: so_output/
          retention-days: 3
