name: Build core library (Android arm64-v8a, CMake)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure CMake for Android arm64-v8a
        run: |
          cmake -S src/main/cpp -B build-android-arm64 \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Release
      - name: Build core library
        run: |
          cmake --build build-android-arm64 --config Release -- -j$(nproc)
      - name: Upload .so artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-core-lib
          path: build-android-arm64/**/*.so
