name: Build

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4


    - name: Configure CMake
      run: |
        cd src/main/cpp
        mkdir -p build
        git clone --depth 1 https://github.com/g-truc/glm.git include/glm
        git clone --depth 1 https://github.com/stbrumme/xxhash.git 3rdparty/xxhash
        cmake -B build \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-29 \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_TOOLCHAIN=clang
    - name: Build
      run: cmake --build src/main/cpp/build --config Release --target mobileglues --parallel $(nproc)

    - name: Strip
      run: |
        cd src/main/cpp/build/
        $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip libmobileglues.so
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: MobileGlues
        path: src/main/cpp/build/libmobileglues.so
